/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c4c7c8",
        "surface-tint": "#c6c6c7",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#e2e2e2",
        "secondary-container": "#00a2e6",
        "inverse-primary": "#5d5f5f",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed": "#001e2f",
        "secondary-fixed": "#c9e6ff",
        "secondary-fixed-dim": "#89ceff",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-container": "#636565",
        "tertiary": "#ffffff",
        "inverse-on-surface": "#313030",
        "surface": "#131313",
        "background": "#131313",
        "primary": "#ffffff",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary-fixed-variant": "#004c6e",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00344e",
        "on-secondary": "#00344d",
        "tertiary-container": "#e2e2e2",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-tertiary-container": "#636565",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "outline": "#8e9192",
        "on-tertiary": "#2f3131",
        "on-tertiary-fixed-variant": "#454747",
        "secondary": "#89ceff",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-fixed-variant": "#454747",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-error": "#690005",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#c6c6c7",
        "outline-variant": "#444748",
        "glass-border": "rgba(255, 255, 255, 0.1)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "element-padding-y": "1.25rem",
        "stack-gap": "1rem",
        "container-max": "640px",
        "section-padding": "2.5rem",
        "element-padding-x": "1.5rem",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        shimmer: "shimmer 1.5s infinite",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
